name: Terraform Security Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  id-token: write
  contents: read
jobs:
  security-scan:
    name: Terraform Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
- name: Configure AWS credentials
  uses: aws-actions/configure-aws-credentials@v4
  with:
    role-to-assume: arn:aws:iam::305584157343:role/GitHubActionsTerraformRole
    aws-region: us-east-1

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: terraform
          format: table
          exit-code: '1'
          severity: HIGH,CRITICAL
          ignore-unfixed: true
